version: 0.2

phases: 
  install:
    commands:
      - echo install
  pre_build:
    commands:
      - echo prebuild
  build:
    commands:
      - echo build
  post_build:
    commands:
      - echo postbuild